<?php

namespace queasy\db\query;

class SingleInsertQuery extends TableQuery
{
    /**
     * Execute INSERT query.
     *
     * @param array $params Query parameters
     *
     * @return int Insert id generated by database
     *
     * @throws DbException On error
     */
    public function run(array $params = array(), array $options = array())
    {
        $sql = sprintf('
            INSERT  INTO `%s`',
            $this->tableName()
        );

        if (count($params)) {
            $sql = sprintf('
                %s
                VALUES  (%s)',
                $sql,
                rtrim(str_repeat('?, ', count($params)), ', ')
            );
        } else {
            // TIP: Seems like this will work in at least SQLite, MySQL, PostgreSQL. Not sure about others.
            $sql .= ' DEFAULT VALUES';
        }

        $this->setSql($sql);

        return parent::run($params, $options);
    }
}

